[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
cache_path  = "cache_foundry"
optimizer = true
optimizer_runs = 1_000
block_gas_limit = 30_000_000

[fmt]
line_length = 80
tab_width = 4
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
