[profile.default]
evm_version = "osaka"
optimizer = true
optimizer_runs = 25
bytecode_hash = "none" # The metadata hash removed from the bytecode (not the metadata itself).
# uncomment this to inspect storage layouts in build artifacts
# extra_output = ["storageLayout"]
verbosity = 3

src = "src"
out = "out"
libs = ["lib", "node_modules"]
cache_path = "cache"

block_gas_limit = 30_000_000
fuzz = { runs = 256, max_test_rejects = 100_000 }
ffi = true

gas_reports = [
    "VettedGate",
    "PermissionlessGate",
    "Accounting",
    "FeeDistributor",
    "FeeOracle",
    "CSModule",
    "Verifier",
    "ParametersRegistry",
    "AssetRecovererLib",
    "OssifiableProxy",
    "HashConsensus",
]

fs_permissions = [
    { access = "read-write", path = "./out" },
    { access = "read-write", path = "./artifacts" },
    { access = "read", path = "./test/fixtures" },
]

ignored_warnings_from = [
    "src/lib/base-oracle/HashConsensus.sol",
    "test/OssifiableProxy.t.sol",
    "node_modules"
]

[profile.lite]
optimizer = false
fuzz = { runs = 50 }
block_gas_limit = 60_000_000

[profile.ci]
verbosity = 3
eth_rpc_timeout = 120
fuzz = { runs = 10_000, max_test_rejects = 2_000_000 }
block_gas_limit = 60_000_000

[profile.ci_quick]
verbosity = 3
eth_rpc_timeout = 120
fuzz = { runs = 1000, max_test_rejects = 500_000 }

[profile.coverage]
# due to coverage running with optimizer disabled, we need to increase the gas limit
# to fit CSM contract tests in one block
block_gas_limit = 60_000_000

[profile.deploy]
# unknown problem of too high estimated gas usage in the implementation deployment script
# after upgrading forge-std 1.7.6 -> 1.9.5
block_gas_limit = 90_000_000

[profile.upgrades]
extra_output = ["storageLayout"]
build_info = true

[lint]
lint_on_build = false
exclude_lints = [
    # Temporarily silence all existing lint findings; we will re-enable them one by one.
    "asm-keccak256",
    "mixed-case-function",
    "mixed-case-variable",
    "named-struct-fields",
    "pascal-case-struct",
    "erc20-unchecked-transfer",
    "incorrect-shift",
    "unsafe-cheatcode",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
