[profile.default]
solc = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1_000
bytecode_hash = "none" # The metadata hash removed from the bytecode (not the metadata itself).

src = "src"
out = "out"
libs = ["lib", "node_modules"]
cache_path  = "cache"

block_gas_limit = 30_000_000
fuzz = { runs = 256 }

gas_reports = [
    "CSAccounting",
    "CSBondCore",
    "CSBondCurve",
    "CSBondLock",
    "CSEarlyAdoption",
    "CSFeeDistributor",
    "CSFeeOracle",
    "CSModule",
    "CSVerifier",
    "AssetRecovererLib",
]

fs_permissions = [
    { access = "write", path = "./out" },
    { access = "read", path = "./test/fixtures" }
]

[profile.ci]
verbosity = 3
fuzz = { runs = 10_000 }

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
