# Schedule turned off for now
---
name: Regular mainnet tests

on:
  workflow_dispatch:
    inputs:
      notify:
        description: "Notify about test results to the discord channel"
        required: false
        default: false
        type: boolean

env:
  FOUNDRY_PROFILE: ci
  TERM: ansi

jobs:
  bootstrap:
    name: Bootstrap environment
    runs-on: ubuntu-latest
    outputs:
      cache-path: ${{ steps.cache.outputs.path }}
      cache-key: ${{ steps.cache.outputs.key }}
    env:
      JUST_TAG: 1.24.0
    steps:
      - name: Build cache params
        id: cache
        run: |
          echo "path=$CACHE_PATH" >> "$GITHUB_OUTPUT"
          echo "$KEY_INPUT" | md5sum | awk '{print $1}' | xargs -I% echo "key=cargobin-%-${RUNNER_OS}" >> "$GITHUB_OUTPUT"
        env:
          CACHE_PATH: |
            ~/.cargo/bin/
          KEY_INPUT: |
            just:${{env.JUST_TAG}}

      - uses: actions/cache@v4
        id: get-cache
        with:
          path: ${{ steps.cache.outputs.path }}
          key: ${{ steps.cache.outputs.key }}

      - name: Install just
        run: cargo install "just@$JUST_TAG"
        if: steps.get-cache.outputs.cache-hit != 'true'

  test:
    name: Integration & Invariant tests
    runs-on: ubuntu-latest
    needs: bootstrap
    env:
      FORGE_REV: v0.3.0
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/cache@v4
        with:
          path: ${{ needs.bootstrap.outputs.cache-path }}
          key: ${{ needs.bootstrap.outputs.cache-key }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: ${{ env.FORGE_REV }}

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn
          cache-dependency-path: "**/yarn.lock"

      - name: Install dependencies
        run: just deps

      - name: Build
        run: just build --sizes

      - name: Run post-vote tests
        run: just test-post-voting
        env:
          CHAIN: mainnet
          DEPLOY_CONFIG: ./artifacts/mainnet/deploy-mainnet.json
          RPC_URL: ${{ secrets.RPC_URL_MAINNET }}

      - name: Echo embeds to the env variable
        if: ${{ failure() && (github.event_name == 'schedule' || inputs.notify) }}
        run: |
          EMBEDS=$(cat <<EOF
          [
            {
              "title": "Failed mainnet tests! :scream:",
              "url": "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID",
              "description": "Check the logs for more information."
            }
          ]
          EOF
          )
          EMBEDS=$(echo "$EMBEDS" | jq -c .) # Compact JSON representation
          echo "EMBEDS=$EMBEDS" >> $GITHUB_ENV

      - name: Discord notification when fails
        if: ${{ failure() && (github.event_name == 'schedule' || inputs.notify) }}
        uses: lidofinance/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.INVARIANTS_CHECK_DISCORD_WEBHOOK_MAINNET }}
          DISCORD_EMBEDS: ${{ env.EMBEDS }}
