---
name: Tests and Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop

env:
  FOUNDRY_PROFILE: ci
  TERM: ansi

permissions:
  security-events: write

jobs:
  security:
    uses: lidofinance/linters/.github/workflows/security.yml@master
  actions:
    uses: lidofinance/linters/.github/workflows/actions.yml@master

  # Maybe to make it reusable workflow instead?
  bootstrap:
    name: Bootstrap environment
    runs-on: ubuntu-latest
    outputs:
      cache-path: ${{ steps.cache.outputs.path }}
      cache-key: ${{ steps.cache.outputs.key }}
    env:
      FORGE_REV: 03ea54c
      JUST_TAG: 1.24.0
    steps:
      - name: Build cache params
        id: cache
        run: |
          echo "path=$CACHE_PATH" >> "$GITHUB_OUTPUT"
          echo "$KEY_INPUT" | md5sum | awk '{print $1}' | xargs -I% echo "key=cargobin-%-${RUNNER_OS}" >> "$GITHUB_OUTPUT"
        env:
          CACHE_PATH: |
            ~/.cargo/bin/
          KEY_INPUT: |
            forge:${{env.FORGE_REV}}
            just:${{env.JUST_TAG}}

      - uses: actions/cache@v4
        id: get-cache
        with:
          path: ${{ steps.cache.outputs.path }}
          key: ${{ steps.cache.outputs.key }}

      - name: Install just
        run: cargo install "just@$JUST_TAG"
        if: steps.get-cache.outputs.cache-hit != 'true'

      - name: Install forge & anvil
        run: cargo install --git https://github.com/foundry-rs/foundry --rev "$FORGE_REV" --profile release --locked forge anvil
        if: steps.get-cache.outputs.cache-hit != 'true'

  linters:
    name: Linters
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/cache@v4
        with:
          path: ${{ needs.bootstrap.outputs.cache-path }}
          key: ${{ needs.bootstrap.outputs.cache-key }}

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn
          cache-dependency-path: "**/yarn.lock"

      - name: Install dependencies
        run: just deps-dev

      - name: Linters check
        run: just lint

  foundry:
    name: Foundry project
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/cache@v4
        with:
          path: ${{ needs.bootstrap.outputs.cache-path }}
          key: ${{ needs.bootstrap.outputs.cache-key }}

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn
          cache-dependency-path: "**/yarn.lock"

      - name: Install dependencies
        run: just deps

      - name: Build
        run: just build --sizes

      - name: Run unit-tests
        run: just test-unit

      - name: Run local integration tests
        run: just test-local
        env:
          CHAIN: holesky
          RPC_URL: ${{ secrets.RPC_URL_HOLESKY }}

      # TODO: Enable later
      # - name: Check gas report
      #   run: just gas-report && git diff --exit-code GAS.md
      #   env:
      #     RPC_URL: ${{ secrets.RPC_URL }}
